homeRegion: &HOME_REGION eu-west-1
enabledRegions:
  - *HOME_REGION

cloudwatchLogRetentionInDays: 365

managementAccountAccessRole: AWSControlTowerExecution

controlTower:
  enable: true

logging:
  account: LogArchive
  cloudtrail:
    enable: true
    organizationTrail: true
  sessionManager:
    sendToCloudWatchLogs: true
    sendToS3: true

budgets:
  - name: anpost-landing-zone-budget
    timeUnit: MONTHLY
    type: COST
    amount: 700
    includeUpfront: true
    includeTax: true
    includeSupport: true
    includeSubscription: true
    includeRecurring: true
    includeOtherSubscription: true
    includeDiscount: true
    includeCredit: false
    includeRefund: false
    subscribers:
      - subscriptionType: EMAIL
        address: pilarternera1967@gmail.com
