defaultVpc: delete
endpointPolicies: []

transitGateways:
  - name: Central-TGW
    account: Network
    region: eu-west-1
    asn: 65000
    autoAcceptSharingAttachments: enable
    routeTables: []
    shareTargets:
      organizationalUnits:
        - Infrastructure
        - Workloads

vpcs:
  - name: Egress-VPC
    account: Network
    region: eu-west-1
    cidrs:
      - 172.16.0.0/16
    internetGateway: true
    subnets:
      - name: Public-Subnet
        availabilityZones: ['a', 'b']
        ipv4CidrBlock: 172.16.0.0/24
      - name: Firewall-Subnet
        availabilityZones: ['a', 'b']
        ipv4CidrBlock: 172.16.1.0/24
      - name: TGW-Subnet
        availabilityZones: ['a', 'b']
        ipv4CidrBlock: 172.16.2.0/24
    natGateways:
      - name: Egress-NAT-A
        subnet: Public-Subnet
        availabilityZone: 'a'
    transitGatewayAttachments:
      - name: Egress-TGW-Attach
        transitGateway:
          name: Central-TGW
          account: Network
        subnets: 
          - TGW-Subnet
        applianceModeSupport: enable

  - name: PAD-VPC-Prod
    account: Production-PAD
    region: eu-west-1
    cidrs:
      - 10.100.0.0/16
    subnets:
      - name: Private-Subnet-App
        availabilityZones: ['a', 'b']
        ipv4CidrBlock: 10.100.1.0/24
      - name: Private-Subnet-Data
        availabilityZones: ['a', 'b']
        ipv4CidrBlock: 10.100.2.0/24
      - name: TGW-Subnet
        availabilityZones: ['a', 'b']
        ipv4CidrBlock: 10.100.3.0/24
    transitGatewayAttachments:
      - name: PAD-Prod-TGW-Attach
        transitGateway:
          name: Central-TGW
          account: Network
        subnets:
          - TGW-Subnet
    routeTables:
      - name: PAD-Prod-Private-RT
        subnets:
          - Private-Subnet-App
          - Private-Subnet-Data
        routes:
          - name: Default-Route-To-TGW
            destination: 0.0.0.0/0
            target: Central-TGW
    vpcEndpoints:
      - service: s3
        type: Gateway
        routeTableNames: 
          - PAD-Prod-Private-RT
        policy: vpc-endpoint-policies/s3-gateway-endpoint-policy.json

centralNetworkServices:
  delegatedAdminAccount: Network
  networkFirewall:
    rules: []
    policies:
      - name: AnPost-Central-Firewall-Policy
        regions:
          - eu-west-1
        statelessDefaultActions: ['aws:forward_to_sfe']
        statelessFragmentDefaultActions: ['aws:forward_to_sfe']
        statefulRuleGroups: []
    firewalls:
      - name: AnPost-Central-Firewall
        account: Network
        region: eu-west-1
        vpc: Egress-VPC
        subnets:
          - Firewall-Subnet
        firewallPolicy: AnPost-Central-Firewall-Policy
