##############################################################################################################
# For detailed information about Included Services, Features, and Configuration References,                  #
# please review the SecurityConfig class reference in our TypeDoc:                                           #
# https://awslabs.github.io/landing-zone-accelerator-on-aws/latest/user-guide/config/#security-configuration #
##############################################################################################################


# -----------------------------------------------------------------------------------------
# AWS Landing Zone Accelerator - Security Configuration
# Project: An Post Eircode Service Take-on (Test Environment)
# -----------------------------------------------------------------------------------------

# AWS Config configuration for resource auditing
awsConfig:
  enableConfigurationRecorder: true
  aggregation:
    enable: true
    delegatedAdminAccount: Audit

# AÑADIDO: El validador exige una política de contraseñas por defecto
iamPasswordPolicy:
  requireMinimumLength: 14
  passwordReusePrevention: 24
  requireLowercaseCharacters: true
  requireNumbers: true
  requireSymbols: true
  requireUppercaseCharacters: true
  allowUsersToChangePassword: true
  maxPasswordAge: 90

centralSecurityServices:
  delegatedAdminAccount: Audit
  
  ebsDefaultVolumeEncryption:
    enable: true
    excludeRegions: []
    
  s3PublicAccessBlock:
    enable: true
    excludeAccounts: []
    
  scpRevertChangesConfig:
    enable: true

  macie:
    enable: false
    # AÑADIDO: Exigencia del validador aunque Macie esté en false
    publishSensitiveDataFindings: false

  guardduty:
    enable: true
    exportConfiguration:
      enable: true
      destinationType: S3
      exportFrequency: FIFTEEN_MINUTES
    s3Protection:
      enable: true

  securityHub:
    enable: true
    regionAggregation: true
    standards:
      - name: AWS Foundational Security Best Practices v1.0.0
        enable: true

  ssmAutomation:
    enable: true
    # AÑADIDO: Exigencia del validador (lista vacía)
    documentSets: []

cloudWatch:
  encryption:
    enabled: true
  # AÑADIDO: Exigencia del validador (lista vacía)
  alarmSets: []