##############################################################################################################
# For detailed information about Included Services, Features, and Configuration References,                  #
# please review the SecurityConfig class reference in our TypeDoc:                                           #
# https://awslabs.github.io/landing-zone-accelerator-on-aws/latest/user-guide/config/#security-configuration #
##############################################################################################################


# -----------------------------------------------------------------------------------------
# AWS Landing Zone Accelerator - Security Configuration
# Project: An Post Eircode Service Take-on (Test Environment)
# -----------------------------------------------------------------------------------------

awsConfig:
  enableConfigurationRecorder: true
  aggregation:
    enable: true
    delegatedAdminAccount: Audit

# ¡NUEVO! Añadido Access Analyzer para calmar al validador
accessAnalyzer:
  enable: false

# ¡CORREGIDO! Con las variables exactas que pedía el log
iamPasswordPolicy:
  minimumPasswordLength: 14
  hardExpiry: false
  passwordReusePrevention: 24
  requireLowercaseCharacters: true
  requireNumbers: true
  requireSymbols: true
  requireUppercaseCharacters: true
  allowUsersToChangePassword: true
  maxPasswordAge: 90

centralSecurityServices:
  delegatedAdminAccount: Audit
  
  ebsDefaultVolumeEncryption:
    enable: true
    excludeRegions: []
    
  s3PublicAccessBlock:
    enable: true
    excludeAccounts: []
    
  scpRevertChangesConfig:
    enable: true

  macie:
    enable: false
    publishSensitiveDataFindings: false

  guardduty:
    enable: true
    exportConfiguration:
      enable: true
      destinationType: S3
      exportFrequency: FIFTEEN_MINUTES
    s3Protection:
      enable: true

  securityHub:
    enable: true
    regionAggregation: true
    standards:
      - name: AWS Foundational Security Best Practices v1.0.0
        enable: true

  ssmAutomation:
    enable: true
    documentSets: []

cloudWatch:
  encryption:
    enabled: true
  alarmSets: []
  # ¡NUEVO! Añadido para calmar al validador
  metricSets: []